language:
  node_js
node_js:
  - "8"
install:
  - npm install -g yarn
script:
  - yarn
  - yarn build
after_script:
  - git clone "https://${GITHUB_TOKEN}@${GITHUB_REPO}"
  - cd noname4me.github.io
  - mkdir -p solutions/mind-map
  - cp -Rf ../build/* ./
  - git add .
  - git commit -m "update Blog"
  - git push