language:
  node_js
node_js:
  - "8"
install:
  - npm install -g yarn
script:
  - yarn
  - yarn build
deploy:
  repo: noname4me/noname4me.github.io
  keep_history: true
  target_branch: master
  provider: pages
  skip_cleanup: true
  local_dir: build/  # or remove this line to upload from root of repo
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master